name: nft_app
description: A new Flutter project which will serve as a template for cards and glass morphism.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  navigation_dot_bar: ^0.1.3
  dot_navigation_bar: ^1.0.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/apiens_1.png
    - lib/assets/images/apiens_2.png
    - lib/assets/images/apiens_3.png
    - lib/assets/images/apiens_4.jpg
#    - directory/subdirectory/





